# Generated by Django 5.0.6 on 2024-07-04 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicle", "0003_alter_moto_options_milage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="milage",
            name="car",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vehicle.car",
                verbose_name="Машина",
            ),
        ),
        migrations.AlterField(
            model_name="milage",
            name="moto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vehicle.moto",
                verbose_name="Мотоцикл",
            ),
        ),
    ]
